### PR TITLE
Added route tag

### PR DESCRIPTION
**Pull request by tburschka**
This pr will add support for the "@route" tag. This could be useful in environments, where the log is parsed and grouped by the route (e.g. Grafana).

### CODE REVIEW

**Comment by faabiosr** [comment]
Hi! Thanks for the contribution.

I wondering if the `logRoute` method has the same data of `logPath`, could you please create a test or improve them for this case?

**Comment by faabiosr** [comment]
Looks great!
Just one small adjustment, inside of each logger will you see the docs of adding fields, could you please update this part by adding the route?

And the last one, I promise 😊, just squash all commits please.

**Comment by tburschka** [comment]
Does github not having a squash featurue during merge by the owner?

**Comment by faabiosr** [comment]
Still showing 5 commits, and unfortunately this repo does not have the squash feature enabled.

**Comment by tburschka** [comment]
I made a new one.... #20

**Pull request closed without merging**
